on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: |
          cp -r src fishing && zip -r release.zip fishing
      - name: Release
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}